### ISSUE TITLE
Importing this project in IntellijIdea is failing

### ISSUE THREAD

**Issue by anshulbajpai** [hmrc/jenkins-job-builders#12]
Importing this project in IntellijIdea fails because it is looking for `.bintray/.credentials` file in home directory which might not be present on every machine and throwing an exception if file not found -  https://github.com/anshulbajpai/jenkins-job-builders/blob/master/build.gradle#L60

Fix - Can possibly create a new file if file does not exist.

**Comment by agilestevesmith** [comment]
Fixed in 7.1.0
