### ISSUE TITLE
Provide a mechanism for creating blocking jobs trigger build step

### ISSUE THREAD

**Issue by anshulbajpai** [hmrc/jenkins-job-builders#13]
Provide a mechanism for creating blocking jobs trigger build step.

ACs

Given a master job which depends on 3 other sub-jobs
When all the 3 sub-jobs finish successfully
Then the status of master job is success

Given a master job which depends on 3 other sub-jobs
When any of the 3 sub-jobs fails
Then the status of master job is failure 

This can help in parallelizing multiple functional suits.

**Comment by anshulbajpai** [comment]
Created a pull request for above issue -

https://github.com/hmrc/jenkins-job-builders/pull/14

**Comment by agilestevesmith** [comment]
Thanks @anshulbajpai. As discussed offline we will give this change a pass as it has not been requested by multiple teams internally, and is a probable smell of slow builds

For future reference see https://github.com/hmrc/mdtp-contributor-guidelines/blob/master/CONTRIBUTING.md
