### ISSUE TITLE
job-dsl-core dependency upgrade

### ISSUE THREAD

**Issue by sanintel3** [hmrc/jenkins-job-builders#18]
Hey folks,
It's more of question than an issue. Are there any plans in pipeline to support latest version of job-dsl-core? 

I'm trying to install a plugin (github pull request builder plugin) and it's enforcing jobs-dsl version to be > 1.3.9. 
When I upgrade jobs-dsl plugin in Jenkins, jenkins seed job is failing with below error
{code}
ERROR: (JobBuilder.groovy, line 136) No signature of method: jobs.job() is applicable for argument types: (uk.gov.hmrc.jenkinsjobbuilders.domain.builder.JobBuilder$_build_closure1) values: [uk.gov.hmrc.jenkinsjobbuilders.domain.builder.JobBuilder$_build_closure1@2509cd45]
Possible solutions: job(java.lang.String), job(java.lang.String, groovy.lang.Closure), run(), run(), any(), use([Ljava.lang.Object;)
{code}

It looks like jenkins-job-builders are not compatible with jobs-dsl-core version 1.39
 
Thanks in advance

**Comment by agilestevesmith** [comment]
Hi @sanintel3, thanks for asking - we will upgrade at some point but I don't expect it to happen within the next few months. We're aware that we're far behind but what we have works well for us. As HMRC Coding In The Open not Open Source we often fall behind on third party deps.

If you want to fork the repo and host your own forked artifacts, go for it. HTH

**Comment by eddgrant** [comment]
Hi @sanintel3,

Not sure if you rolled your own solution in the end but we've just released v11.0.0 which upgrades to v1.68 of the job-dsl-plugin. It's available [in bintray](https://bintray.com/hmrc/releases/jenkins-job-builders/11.0.0) now.

Hope that helps,

Edd

**Comment by eddgrant** [comment]
Closing this issue.

**Comment by sanintel3** [comment]
@eddgrant @SteveSmithCD Thanks for the response and update, For some reason I had missed earlier notifications and hence couldn't respond
